### ISSUE TITLE
Doesn't work with Appwrite 9.0.1

### ISSUE THREAD

**Issue by skyface753** [DiegoBM/react-native-appwrite-oauth#1]
Hello,

It seems like the package doesn't work with the newest appwrite version. I already tried to update the dependencies myself, but I dont get it.

xD

**Comment by DiegoBM** [comment]
Apologies, I never received an email about this, which is usually how I know that something is going on with Gihub...

Indeed Appwrite has changed the way they instantiate the SDK, so the library was not working anymore. That and also in the past two years hermes became the standard engine, which also brought some problems with regular expressions. That all should be fixed now. I've tested it with Github OAuth and it seems to work well. I was going to try with Facebook but they have implemented now a limitation to prevent from logging in from embedded browsers by default, and you need to change a setting in your Facebook profile to allow it, which I didn't know where to find.

I've pulled off an all-nighter trying to upgrade the react-native example application with two years of changes (which is a nightmarish task) together with the library, so hopefully I haven't messed up too much.
If you try to run the example app and it fails because metro is not running, just run it again and it will work. Metro has always been so temperamental.

Note: It's worth mentioning that as of 2022, using a WebView is not the recommended way to do OAuth in mobile anymore. I expand a bit more on this in this issue: https://github.com/appwrite/sdk-for-react-native/issues/10
